name: main

on:
  push:
    branches: [ master, test-me-* ]
    tags:
  pull_request:

jobs:
  main-windows:
    uses: asottile/workflows/.github/workflows/tox.yml@v1.0.0
    with:
      env: '["py311"]'
      os: windows-latest
  main-linux:
    uses: asottile/workflows/.github/workflows/tox.yml@v1.0.0
    with:
      env: '["py311"]'
      os: ubuntu-latest
